### ISSUE TITLE
WinError 126 after building during execution *.exe

### ISSUE THREAD

**Issue by 573N** [NaturalHistoryMuseum/pyzbar#33]
pyzbar 0.1.7
Python 3.4.4
py2exe 0.9.2.2

Traceback (most recent call last):
  File "c:\python34\lib\site-packages\pyzbar\zbar_library.py", line 58, in load
    dependencies, libzbar = load_objects(Path(''))
  File "c:\python34\lib\site-packages\pyzbar\zbar_library.py", line 52, in load_objects
    for dep in dependencies
  File "c:\python34\lib\site-packages\pyzbar\zbar_library.py", line 52, in <listcomp>
    for dep in dependencies
  File "c:\python34\lib\ctypes\__init__.py", line 429, in LoadLibrary
    return self._dlltype(name)
  File "c:\python34\lib\ctypes\__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Das angegebene Modul wurde nicht gefunden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "RecIT.pyw", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "c:\python34\lib\site-packages\pyzbar\pyzbar.py", line 7, in <module>
    from .wrapper import (
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "c:\python34\lib\site-packages\pyzbar\wrapper.py", line 148, in <module>
    c_uint_p,    # minor
  File "c:\python34\lib\site-packages\pyzbar\wrapper.py", line 141, in zbar_function
    return prototype((fname, load_libzbar()))
  File "c:\python34\lib\site-packages\pyzbar\wrapper.py", line 120, in load_libzbar
    libzbar, dependencies = zbar_library.load()
  File "c:\python34\lib\site-packages\pyzbar\zbar_library.py", line 60, in load
    dependencies, libzbar = load_objects(Path(__file__).parent)
  File "c:\python34\lib\site-packages\pyzbar\zbar_library.py", line 52, in load_objects
    for dep in dependencies
  File "c:\python34\lib\site-packages\pyzbar\zbar_library.py", line 52, in <listcomp>
    for dep in dependencies
  File "c:\python34\lib\ctypes\__init__.py", line 429, in LoadLibrary
    return self._dlltype(name)
  File "c:\python34\lib\ctypes\__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Das angegebene Modul wurde nicht gefunden

**Comment by 573N** [comment]
looks like this: https://github.com/NaturalHistoryMuseum/pyzbar/issues/13
i have installed  Visual C++ Redistributable Packages for Visual Studio 2013 but same problem :(

**Comment by quicklizard99** [comment]
It is likely that the DLLs (32-bit: `libzbar-32.dll` and `libiconv-2.dll`; 64-bit: `libzbar-64.dll` and `libiconv.dll`) have not been included in the build created by py2exe.

* I am not familiar with py2exe - is there a way to add DLLs to the build?
* zbar exposes binary dependencies in `EXTERNAL_DEPENDENCIES`, which you might be able to use: https://github.com/NaturalHistoryMuseum/pyzbar/issues/27#issuecomment-383159740

**Comment by 573N** [comment]
ok, i copy libzbar-64.dll and libiconv.dll to the build and new error but not from pyzbar :(

I know it's not a problem with pyzbar anymore but maybe it helps others

Traceback (most recent call last):
  File "c:\python34\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: (DLL load failed: Das angegebene Modul wurde nicht gefunden.) 'E:\\git_aktuell\\RecIT\\dist\\numpy.core.multiarray.pyd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "RecIT.pyw", line 7, in <module>
  File "c:\python34\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "c:\python34\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "c:\python34\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "c:\python34\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "c:\python34\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: (DLL load failed: Das angegebene Modul wurde nicht gefunden.) 'E:\\git_aktuell\\RecIT\\dist\\numpy.core.multiarray.pyd'

**Comment by 573N** [comment]
ok i have a workaround, not nice but works

py2exe does not work and so I use pyinstaller

libiconv.dll, libzbar-64.dll and opencv_ffmpeg341_64.dll(for cv2) must be in the exe folder

please close
