### ISSUE TITLE
Too many values to unpack

### ISSUE THREAD

**Issue by TheDevKiller** [NaturalHistoryMuseum/pyzbar#35]
>>> img = requests.get("https://liketomove.it/defi-qr/la_solution_c_est_pas_3.jpg")
>>> print(decode(img))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/thedevkiller/.local/lib/python3.6/site-packages/pyzbar/pyzbar.py", line 180, in decode
    pixels, width, height = _pixel_data(image)
  File "/home/thedevkiller/.local/lib/python3.6/site-packages/pyzbar/pyzbar.py", line 145, in _pixel_data
    pixels, width, height = image
ValueError: too many values to unpack (expected 3)

**Comment by HiroyukiInamoto** [comment]
>   File "/usr/local/lib/python3.7/site-packages/pyzbar/pyzbar.py", line 180, in decode
    pixels, width, height = _pixel_data(image)
  File "/usr/local/lib/python3.7/site-packages/pyzbar/pyzbar.py", line 145, in _pixel_data
    pixels, width, height = image
ValueError: too many values to unpack (expected 3)

I got same message. Strangely, it doesn't occur using interpreter.

**Comment by quicklizard99** [comment]
Apologies for my rather late response.

The `decode` checks the image to see if it is either a PIL image or a `numpy` `ndarray`. If it is neither, it assumes that it is a tuple of three elements - (pixels, width, height).

In this case `img` is of type `<class 'requests.models.Response'>`. The simplest thing is to use PIL (via Pillow https://pillow.readthedocs.io/en/stable/):

```
>>> from io import BytesIO
>>> from PIL import Image
>>> img = Image.open(BytesIO(img.content))
>>> print(decode(img))
[Decoded(data=b'L4_51MpLIcIT3_E5T_Un_D35_C4r4C7ER35_dU_gEN13.', type='QRCODE', rect=Rect(left=20, top=20, width=225, height=225), polygon=[Point(x=20, y=20), Point(x=21, y=244), Point(x=245, y=245), Point(x=244, y=21)])]
```

**Comment by TheDevKiller** [comment]
Ok I'll try it thank you
